CREATE TABLE public.accounts (
  Account_ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Document_Number VARCHAR UNIQUE NOT NULL,
  CONSTRAINT pk_accounts PRIMARY KEY (Account_ID)
);

CREATE TABLE public.operation_types (
  Operation_Type_ID INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Description VARCHAR NOT NULL,
  CONSTRAINT pk_operationtypes PRIMARY KEY (Operation_Type_ID)
);

CREATE TABLE public.transactions (
  Transaction_ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Amount NUMERIC NOT NULL,
  Event_Date TIMESTAMP NOT NULL DEFAULT NOW(),
  Account_ID BIGINT NOT NULL,
  Operation_Type_ID INTEGER NOT NULL,
  CONSTRAINT pk_transactions PRIMARY KEY (Transaction_ID),
  CONSTRAINT fk_account FOREIGN KEY(Account_ID) REFERENCES public.accounts(Account_ID),
  CONSTRAINT fk_operation_types FOREIGN KEY(Operation_Type_ID) REFERENCES public.operation_types(Operation_Type_ID)
);

INSERT INTO public.operation_types(Operation_Type_ID, Description) VALUES(1, 'COMPRA A VISTA');
INSERT INTO public.operation_types(Operation_Type_ID, Description) VALUES(2, 'COMPRA PARCELADA');
INSERT INTO public.operation_types(Operation_Type_ID, Description) VALUES(3, 'SAQUE');
INSERT INTO public.operation_types(Operation_Type_ID, Description) VALUES(4, 'PAGAMENTO');
